2024-04-18 18:29:00,724 : INFO : root : Loading config.
2024-04-18 18:29:00,727 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-04-18 18:29:00,727 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/871505f0f2d2915bd502f0a1fb110f3b.mpf_cache
2024-04-18 18:29:00,749 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-18 18:29:00,749 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/edcc5f1d3215b377c9faab88c62e4ce0.mpf_cache
2024-04-18 18:29:00,750 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/640347d32029b3f32c9ad31d7a1b4b81.mpf_cache
2024-04-18 18:29:00,750 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f97c90855879603280fcc571f5c42639.mpf_cache
2024-04-18 18:29:00,750 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/1875c266911f801b691956fe9e9284d6.mpf_cache
2024-04-18 18:29:00,750 : INFO : ConfigProcessor : Loading config from file /Users/tannerpetch/Documents/GitHub/lofab/modes/ball_started_shows/config/ball_started_shows.yaml.
2024-04-18 18:29:00,752 : INFO : ConfigProcessor : Loading config: /Users/tannerpetch/Documents/GitHub/lofab/modes/ball_started_shows/config/ball_started_shows.yaml
2024-04-18 18:29:00,752 : INFO : ConfigProcessor : Config file cache created: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/dc654dabef444957b27720f6742c211f.mpf_cache
2024-04-18 18:29:00,752 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/3dbc438e88423aa3ff742db2713b600f.mpf_cache
2024-04-18 18:29:00,753 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/91adfe62d94491e9c757b00a8e3b96af.mpf_cache
2024-04-18 18:29:00,753 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/154d071a3850556c6f3eae37bf41c8b6.mpf_cache
2024-04-18 18:29:00,754 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/ab100dbe0e16472b56f0213f3842a00f.mpf_cache
2024-04-18 18:29:00,756 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/f03ad90ccd2c053e9e5d10795d01f4ba.mpf_cache
2024-04-18 18:29:00,756 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/0f3c951d4c93079ae3fac6429c5bc2ee.mpf_cache
2024-04-18 18:29:00,756 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/8bf004783a280ac33d17b88f37848116.mpf_cache
2024-04-18 18:29:00,758 : INFO : ConfigProcessor : Loading config from cache: /var/folders/l2/q8hj_6s91xnb2jxg1sqm0h7r0000gn/T/d5d50eaa09e055f3a827c6269a3aa165.mpf_cache
2024-04-18 18:29:00,759 : INFO : Machine : Mission Pinball Framework Core Engine v0.57.1.dev3
2024-04-18 18:29:00,759 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': True, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-04-18-18-29-00-mpf-Tanners-Laptop.local.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False}
2024-04-18 18:29:00,759 : INFO : Machine : MPF path: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf
2024-04-18 18:29:00,759 : INFO : Machine : Machine path: /Users/tannerpetch/Documents/GitHub/lofab
2024-04-18 18:29:00,759 : INFO : Machine : Platform: darwin
2024-04-18 18:29:00,759 : INFO : Machine : Python executable location: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9
2024-04-18 18:29:00,759 : INFO : Machine : Python version: 3.9.13 (64-bit)
2024-04-18 18:29:00,759 : INFO : Machine : Initializing MPF...
2024-04-18 18:29:00,788 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,801 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-04-18 18:29:00,801 : INFO : EventManager : Event: ======'machine_var_player1_score'====== Args={'value': 0, 'prev_value': None, 'change': True}
2024-04-18 18:29:00,801 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,801 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.57.1.dev3, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,801 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.9.13', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'macOS-14.3-arm64-arm-64bit', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Darwin', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '23.3.0', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': 'Darwin Kernel Version 23.3.0: Thu Dec 21 02:29:41 PST 2023; root:xnu-10002.81.5~11/RELEASE_ARM64_T8122', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'arm64', 'prev_value': None, 'change': True}
2024-04-18 18:29:00,810 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-04-18 18:29:00,824 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-04-18 18:29:00,826 : INFO : EventManager : Event: ======'bcp_connection_attempt'====== Args={'name': 'local_display', 'host': 'localhost', 'port': 5050}
2024-04-18 18:29:00,826 : INFO : BCPClientSocket : Connecting BCP to 'local_display' at localhost:5050...
2024-04-18 18:29:01,746 : INFO : BCPClientSocket : Connected BCP to 'local_display' localhost:5050
2024-04-18 18:29:01,746 : INFO : EventManager : Event: ======'bcp_clients_connected'====== Args={}
2024-04-18 18:29:01,748 : INFO : ball_device.bd_vuk : BCH: Initial count: 0
2024-04-18 18:29:01,748 : INFO : ball_device.bd_vuk : State: idle
2024-04-18 18:29:01,748 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2024-04-18 18:29:01,748 : INFO : ball_device.bd_trough : State: idle
2024-04-18 18:29:01,754 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-04-18 18:29:01,907 : INFO : EventManager : Event: ======'machine_var_mc_version'====== Args={'value': 'MPF-MC v0.57.0', 'prev_value': None, 'change': True}
2024-04-18 18:29:01,907 : INFO : EventManager : Event: ======'machine_var_mc_extended_version'====== Args={'value': 'MPF-MC v0.57.0 (config_version=6, BCP v1.1,                      Requires MPF API compatibility v0.57.0 or newer)', 'prev_value': None, 'change': True}
2024-04-18 18:29:01,908 : ERROR : asyncio : Exception in callback EventManager._queue_task_done(<Task finishe... your step?')>)
handle: <Handle EventManager._queue_task_done(<Task finishe... your step?')>)>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 125, in load
    self._show_validation_error("Show {} does not appear to be a valid show "
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "launch_lights" >> Show launch_lights does not appear to be a valid show config. It should be a list of steps. Did you forget the hyphen at the start of your step? Context: launch_lights Error Code: CFE-show-1 (https://missionpinball.org/logs)
2024-04-18 18:29:01,918 : INFO : Machine : Starting the main run loop.
2024-04-18 18:29:01,918 : INFO : Machine : Shutting down...
2024-04-18 18:29:01,918 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-04-18 18:29:02,920 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 795, in _queue_task_done
    future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/events.py", line 708, in _run_handlers_sequential
    handler.callback(queue=queue, **merged_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/core/show_controller.py", line 53, in _load_shows
    self.machine.shows[show_name].load(show_config)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 125, in load
    self._show_validation_error("Show {} does not appear to be a valid show "
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/mpf/assets/show.py", line 184, in _show_validation_error
    raise ConfigFileError('"{}" >> {}'.format(self.name, msg), error_code, "show", self.name)
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in show: "launch_lights" >> Show launch_lights does not appear to be a valid show config. It should be a list of steps. Did you forget the hyphen at the start of your step? Context: launch_lights Error Code: CFE-show-1 (https://missionpinball.org/logs)
2024-04-18 18:29:19,069 : INFO : root : MPF run loop ended.
